flowchart TD
    A(( )) --> B{"¿Ya es cliente?"} 
    B--> |Sí| C("Inicio de sesión") 
    B--> |No| D("Creación de cuenta")
    C--> Z((( )))
    D--> E("Rellenar formulario de registro")
    E--> F{"¿Los datos son válidos?"}
    F--> |Sí| G(Cuenta creada correctamente)
    F--> |No| E
    G --> Z

 style A fill:#000000,stroke:#000000,color:#ffffff
 style Z fill:#000000,stroke:#000000,color:#ffffff